"""empty message

Revision ID: 4cfade125b4c
Revises: 
Create Date: 2019-09-09 18:14:30.256545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfade125b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PageViews',
    sa.Column('view_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('view_num')
    )
    op.create_index(op.f('ix_PageViews_ip_address'), 'PageViews', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PageViews_ip_address'), table_name='PageViews')
    op.drop_table('PageViews')
    # ### end Alembic commands ###
